get values from dedicated events-scrape secret
openshift-assisted/assisted-events-scrape pull request #19
Opened 2021-11-14 18:07 UTC by michaellevy101

2021-11-14 18:07 UTC, michaellevy101 commented
/hold pending to https://gitlab.cee.redhat.com/service/app-interface/-/merge_requests/28640

2021-11-14 18:07 UTC, michaellevy101 commented
/cc @osherdp

2021-11-14 18:32 UTC, osherdp requested changes
Can you add some description to the PR?
I'm not sure I understand how it will be used when deployed on the environment

2021-11-14 18:32 UTC, osherdp commented on README.md
> +
seems unused, no?

2021-11-21 09:51 UTC, michaellevy101 commented on README.md
> +
used by the AI client

2021-11-21 09:54 UTC, michaellevy101 commented
/unhold

2021-11-21 10:05 UTC, osherdp approved these changes

2021-11-21 10:06 UTC, merged